#!/usr/bin/env bash
# script Bash que transfiera un archivo de nuestro cliente a un servidor

if [[ $# -ne 4 ]]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~/
fi
