#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 serve
sudo apt-get -y update
sudo apt-get install -y haproxy=1.6\*
FILE=/etc/haproxy/haproxy.cfg
echo "listen 1464-lb-01" | sudo tee -a $FILE
echo "bind *:80" | sudo tee -a $FILE
echo "mode http" | sudo tee -a $FILE
echo "balance roundrobin" | sudo tee -a $FILE
echo "server 1466-web-01 35.243.141.246 check" | sudo tee -a $FILE
echo "server 1466-web-02 54.227.41.202 check" | sudo tee -a $FILE
sudo service haproxy restart
