#!/usr/bin/env bash
# This script that displays Holberton School 10 times,
CONT=0
while [  $CONT -lt 10 ];
do
    echo "Holberton School"
    if [ $CONT = 8 ];
    then
        echo "Hi"
    fi
    (( CONT = CONT + 1 ))
    done
