#!/usr/bin/env bash
# This script that loops from 1 to 10
CONT=0
while [  $CONT -lt 8 ];
do
    echo "Holberton School"
    if [ $CONT = 2 ];
    then
        echo "bad luck"

    elif [ $CONT = 5 ];
    then
        echo "good luck"
    fi
    let CONT = CONT + 1
    done
