#!/usr/bin/env bash
# This script that loops from 1 to 10
CONT=1
while [ $CONT -lt 11 ]
do
    if [ $CONT = 4 ]
    then
        echo "bad luck"
    elif [ $CONT = 8 ]
    then
        echo "good luck"
    else
        echo "Holberton School"
    fi
    (( CONT = CONT + 1 ))
done
