#!/usr/bin/env bash
# This script that displays numbers from 1 to 20
CONT=1
while [  $CONT -lt 21 ];
do
    echo $CONT
    if [ $CONT = 4 ];
    then
        echo "bad luck from China"

    elif [ $CONT = 9 ];
    then
        echo "bad luck from Japan"

    elif [ $CONT = 17 ];
    then
        echo "bad luck from Italy"
    fi
    (( CONT = CONT + 1 ))
done
